version: '3.2'
services:
  db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - "./initdb:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

volumes:
  pg_data:
